site_name: parcel

theme:
  name: material
  icon:
    logo: material/inbox
  favicon: images/favicon.png
  palette:
    scheme: default
    primary: blue grey
    accent: blue grey
  font:
    text: Raleway
    code: JetBrains Mono
  features:
    - navigation.instant
    - search.suggest

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/JohnCoene/parcel
repo_name: Github
site_description: Parcel.js for R.
site_author: John Coene
copyright: Copyright &copy; 2021 John Coene

google_analytics:
  - UA-74544116-1
  - auto

markdown_extensions:
    - admonition
    - meta
    - smarty
    - pymdownx.highlight:
        linenums: true
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - attr_list
    - toc:
        permalink: True
        separator: "-"

nav:
  - Home: index.md
  - Installation: installation.md
  - Engine: engine.md
  - Example: example.md
